# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-28 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0002_remove_profile_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.ImageField(default='pics/default.jpg', upload_to='pics/'),
        ),
    ]
