# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-25 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0003_auto_20191025_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='pub_date',
        ),
    ]
