# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-29 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0004_auto_20191028_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='vote_submissions',
            field=models.IntegerField(default=0),
        ),
    ]
