# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-25 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0004_remove_project_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='design',
            field=models.IntegerField(default=0),
        ),
    ]
