# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-30 06:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0006_auto_20191029_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
