# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-26 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
    ]
