# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-30 07:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0007_remove_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
    ]
